"""Replay storage helpers for live operator commands."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Literal

from .replay_metadata import (
    OPERATOR_COMMAND_DATASET_CAPABILITY,
    OPERATOR_COMMAND_DATASET_ID,
    OPERATOR_COMMAND_TABLE_NAME,
    ReplayDatasetSpec,
)
from .replay_writer import ReplayWriter
from .table_schema import ColumnDef, TableSchema

OperatorCommandStatus = Literal["completed", "failed", "cancelled", "timeout"]


def operator_command_columns() -> list[ColumnDef]:
    return [
        ColumnDef(
            "command_id",
            "TEXT",
            nullable=False,
            logical_type="id",
            description="Stable command id generated by the live operator API.",
        ),
        ColumnDef(
            "type",
            "TEXT",
            nullable=False,
            enum_values=["ask", "intervene"],
            description="Operator command type.",
        ),
        ColumnDef(
            "step",
            "INTEGER",
            nullable=False,
            logical_type="step",
            analysis_role="timestamp",
            description="Simulation step count when the command completed.",
        ),
        ColumnDef(
            "simulation_time",
            "TIMESTAMP",
            nullable=False,
            logical_type="timestamp",
            analysis_role="timestamp",
            description="Simulation timestamp when the command completed.",
        ),
        ColumnDef(
            "prompt",
            "TEXT",
            nullable=False,
            description="Question or instruction entered by the operator.",
        ),
        ColumnDef(
            "target_json",
            "JSON",
            nullable=False,
            logical_type="json",
            description="Normalized command target payload.",
        ),
        ColumnDef(
            "result",
            "TEXT",
            nullable=False,
            description="Command result returned by the live session.",
        ),
        ColumnDef(
            "artifact_name",
            "TEXT",
            description="Human-readable artifact file written for this command.",
        ),
        ColumnDef(
            "status",
            "TEXT",
            nullable=False,
            enum_values=["completed", "failed", "cancelled", "timeout"],
            description="Final command status.",
        ),
        ColumnDef(
            "created_at",
            "TIMESTAMP",
            nullable=False,
            logical_type="timestamp",
            description="Wall-clock time when the command row was recorded.",
        ),
    ]


async def register_operator_command_dataset(writer: ReplayWriter) -> None:
    columns = operator_command_columns()
    await writer.register_table(
        TableSchema(
            name=OPERATOR_COMMAND_TABLE_NAME,
            columns=columns,
            primary_key=["command_id"],
            indexes=[["step"], ["simulation_time"], ["type"]],
        )
    )
    await writer.register_dataset(
        ReplayDatasetSpec(
            dataset_id=OPERATOR_COMMAND_DATASET_ID,
            table_name=OPERATOR_COMMAND_TABLE_NAME,
            module_name="LiveExperiment",
            kind="event_stream",
            title="Operator Commands",
            description="Recorded ask/intervene commands issued during a live run.",
            entity_key="command_id",
            step_key="step",
            time_key="simulation_time",
            default_order=["step", "created_at", "command_id"],
            capabilities=[
                OPERATOR_COMMAND_DATASET_CAPABILITY,
                "event_stream",
                "timeseries",
            ],
        ),
        columns,
    )


async def write_operator_command(
    writer: ReplayWriter,
    *,
    command_id: str,
    command_type: Literal["ask", "intervene"],
    step: int,
    simulation_time: datetime,
    prompt: str,
    target: dict[str, Any] | None,
    result: str,
    artifact_name: str | None,
    status: OperatorCommandStatus,
    created_at: datetime | None = None,
) -> None:
    await register_operator_command_dataset(writer)
    await writer.write(
        OPERATOR_COMMAND_TABLE_NAME,
        {
            "command_id": command_id,
            "type": command_type,
            "step": step,
            "simulation_time": simulation_time,
            "prompt": prompt,
            "target_json": target or {},
            "result": result,
            "artifact_name": artifact_name,
            "status": status,
            "created_at": created_at or datetime.now(timezone.utc),
        },
    )
